#                                _      _     _        
#                               | |    | |   (_)       
#   __ _   ___  _ __  ___   ___ | |__  | | __ _  _ __  
#  / _` | / _ \| '__|/ __| / __|| '_ \ | |/ /| || '_ \ 
# | (_| ||  __/| |   \__ \| (__ | | | ||   < | || | | |
#  \__, | \___||_|   |___/ \___||_| |_||_|\_\|_||_| |_|
#   __/ |                                              
#  |___/                                               
#
# Server Version 0.0.0

[rpc]
host = "127.0.0.1"
port = 5050
